@startuml

skinparam linetype ortho



frame "Core_Schema" {

    entity "resources" as res {
        *id : integer <<generated>>
        *name : string
        --
        *definition_id : integer
        *value : bytea
        lease : integer
    }

    entity "revision_logs" as resrev {
        *revision : integer <<generated>>
        *previous_revision : integer
        *operation : enum {create, update, delete}
        *log_data  : bytea
        --
        *resource_id : integer
        *resource_name : string
    }

    /' supported value definition types are:
        - TableDefinition
        - JsoncDefinition
        - JsonDefinition
        - AvroDefinition
        - FileDefinition
        - RawByteDefinition '/
    entity "resource_type" as restype {
        *id : integer <<generated>>
        *name : name
        *schema : jsonb
    }


    entity "resource_definitions" as valdef {
        *id : integer <<generated>>
        *name : string <<unique>>
        *type_id : integer
        *definition : jsonb
    }

    res ||--o{ resrev
    resrev |o--|| resrev
    valdef ||--o{ res
    restype ||--o{ valdef


    entity "json_values" as jsonval {
        *id : integer <<generated>>
        --
        *resource_id : integer
        *value : jsonb
    }

    res ||--|| jsonval

    frame "Custom_Table_Schema" {
        entity "custom_table_1" {
            ...
        }

        entity "custom_table_2" {
            ...
        }
    }
}
@enduml













