@startuml

'https://plantuml.com/component-diagram

'skinparam defaultFontSize 20

database "DataSource"

component "Ingestor"

component "SourcePort"

component "Processor"

component "SinkPort"

component "Loader"

database "DataStore"

[DataSource] -r-> [Ingestor]: tx_logs
[Ingestor] -r-> [SourcePort]: change_records
[SourcePort] -r-> [Processor]: transact_records
[Processor] --> [SinkPort]: harmonized_records
[SinkPort] -l-> [Loader]: to_load_records
[Loader] -l-> [DataStore]: update_queries

@enduml