@startuml
skinparam linetype ortho
skinparam fixCircleLabelOverlapping true

frame Loader {
    component LoadingQueue
    component Validator
    component QueryRunner

    LoadingQueue --> Validator
    Validator --> QueryRunner
}

interface FailToleranceByReplay
interface RecordTypeRegistry

Loader .r.> FailToleranceByReplay
Loader .r.> RecordTypeRegistry

component Neo4jServer_1...N
QueryRunner --> Neo4jServer_1...N
@enduml